package businessLogic;
import connection.ConnectionFactory;
import java.util.ArrayList;
import model.Product;
import presentationLayer.*;
import connection.DataAccessClass;

public class ProductBLL {
    private ArrayList<Product> products;
    private DataAccessClass<Product> productDAO;
    private MainFrame mainFrame;
    private int newID;


    public int getNewID()
    {
        return newID;
    }

    /**
     * Creates a new instance of ProductBLL.
     * @param connectionFactory is the object holding the connection to the database.
     * @param mainFrame is the main window of the application, which will have to be updated in this class when client changes are made.
     */
    public ProductBLL(ConnectionFactory connectionFactory, MainFrame mainFrame)
    {
        this.mainFrame=mainFrame;
        productDAO= new DataAccessClass<Product>(connectionFactory, new Product(), mainFrame);
        products= productDAO.findAll();
        if(products.isEmpty())
            newID = 1;
        else
        newID= products.get(products.size()-1).getId()+1;
    }


    public ArrayList<Product> getProducts() {
        return products;
    }

    /**
     * @param id the id of the product we want to find.
     */
    public Product getProductByID(int id)
    {
        for(int i=0;i<products.size();i++)
            if(products.get(i).getId()==id)
                return products.get(i);
        return null; //not found
    }

    public void updateProduct(Product product)
    {
        productDAO.update(product);
        ((ProductsView)mainFrame.panels[1]).updateTable(products);
    }


    /**
     * Validates the input provided by the user when trying to edit/add a product.
     * If the input is correct, it edits/inserts the new product and makes the neccessary updates in the GUI and in the database.
     * @param id provided a valid integer (not user input but generated by the application).
     * @param name checked to be not empty.
     * @param price checked to be not empty and be a valid float value.
     * @param stock checked to be not empty and be a valid integer value.
     * @return -1 if the input is correct and the updates were made, 0 if the name is incorrect, 1 if the price is incorrect, 2 if the stock is incorrect.
     */
    public int validateProduct(String id, String name, String price, String stock)
    {
        if(name==null || name.isEmpty()) return 0;

        if(price != null && !price.isEmpty()) {
            if(price.length()>10) return 1;
            boolean pointfound=false;
            for(int i=0;i<price.length();i++)
            {
                if(price.charAt(i)=='.')
                    if(!pointfound)
                        pointfound=true;
                    else return 1; //more than 1 point
                else
                if(!Character.isDigit(price.charAt(i))) return 1;
            }
        }else return 1;

        if(stock != null && !stock.isEmpty()) {
            try
            {
                int st=Integer.parseInt(stock);
                if (st<0) return 2;
            }
            catch(NumberFormatException e){ return 2; }
        } else return 2;


        Product product = new Product(Integer.valueOf(id), name, Float.valueOf(price), Integer.parseInt(stock));
        updateProductsList(product);

        return -1;
    }

    private void updateProductsList(Product product)
    {
        int i=0;
        while(i<products.size() && products.get(i).getId()!=product.getId())
            i++;

        if(i==products.size()) //new client
        {
            products.add(product);
            newID++;
            productDAO.insert(product);
        }
        else
        {
            products.set(i,product);
            productDAO.update(product);
        }
        ((ProductsView)mainFrame.panels[1]).updateTable(products);
        ((OrdersView)mainFrame.panels[2]).updateProductsBox(products);
    }


    /**
     * Deletes the product from the application and makes the updates in the GUI and database.
     * @param id the id of the product that will be deleted, provided it is a valid id.
     */
    public void deleteProduct(int id)
    {
        int i=0;
        while(i<products.size() && products.get(i).getId()!=id)
            i++;
        if ( productDAO.deleteByID(id) != -2 ){
            products.remove(i);
            ((ProductsView)mainFrame.panels[1]).updateTable(products);
            ((OrdersView)mainFrame.panels[2]).updateProductsBox(products);
        }
    }



}